### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by lucasantoniooficial** [dclipca/eckmar#1]
There is no module folder in the project, it is registered in the composer but it does not exist, could you find out if this is correct? Because there is an error in the system causing this one of them is in FeaturedProducts

**Comment by virtumonde** [comment]
@lucasantoniooficial can you post the error?

**Comment by lucasantoniooficial** [comment]
@virtumonde No hint path defined for [featuredproducts]. (View: E:\laragon\www\peralta\resources\views\welcome.blade.php)

**Comment by virtumonde** [comment]
@lucasantoniooficial Sorry for the long response. I think that most likely this relates to an incorrect installation, more specifically you didn't run an ```artisan``` command. Can you run all the ```artisan commands``` (I am not sure if there are more than one) and then if it doesn't work, do a new installation.

**Comment by botdigit-admin** [comment]
https://demo.botdigit.com/

this one is running script

**Comment by devprg** [comment]
This is Eckmar's Marketplace script :)

**Comment by dclipca** [comment]
@devprg that's true.

**Comment by dclipca** [comment]
It should work, I tested this one year ago and everything was working perfectly.

**Comment by botdigit-admin** [comment]
files are correct and tested
