### ISSUE TITLE
Laravel Error Monero Issue

### ISSUE THREAD

**Issue by Gralien** [dclipca/eckmar#13]
Hi.
Monero-integration
When I attempt to finalize transactions by pressing the purchase "mark as delivered" on order page the site returns
"error happened, try again later"

But The funds go through and all is correctly transferred and the error persists.

log/laravel
[TIME/DATE] local.ERROR: Purchase xxx :Request have return error: not enough money; 
Request: {"jsonrpc":"2.0","method":"transfer","params":{"destinations":[{"amount":31543530000,"address":"4XXX"}],"mixin":6,"get_tx_key":true,"payment_id":"","account_index":0,"subaddr_indices":"","priority":2,"do_not_relay":false},"id":1};

Purchase wont finalize and mark delivered but the funds are sent. Cant mark sale as delivered on the site even though funds are sent to vendor successfully.

**Comment by Gralien** [comment]
the true error in the stack trace;

"fail timeout json_rpc Error: Operation timed out after 8001 milliseconds"
RPC timeout is triggering site error while the transaction is successful and takes longer than 8 seconds to render results back.

im going to suspect a default timeout of 8 set in 
/app/Marketplace/Utility/MoneroRPC/jsonRPCClient.php

CURLOPT_CONNECTTIMEOUT => 8,
        CURLOPT_TIMEOUT => 8

as the culprit. and adjust accordingly. RPC server seems to be taking 30 + seconds with the intensive logging on.
//On HDD vs SDD, HDD will take more processing time triggering a timeout?
//possible that setting higher RPC server log values slows process even further?

this type of issue could end up being the solution to intermittent RPC connectivity between site and node.

will close issue if successful.

**Comment by Gralien** [comment]
Correct solution;
CURLOPT_CONNECTTIMEOUT => 0,
CURLOPT_TIMEOUT => 0

**Comment by Gralien** [comment]
closed

**Comment by ejinbt** [comment]
hey I changed the timeout values. , still I am getting errors and a new one
"tx is not possible" , sometimes "not enough money"
is this because it is not calculating the fee amount on transfer ?

**Comment by ejinbt** [comment]
hey I changed the timeout values. , still I am getting errors and a new one
"tx is not possible" , sometimes "not enough money"
is this because it is not calculating the fee amount on transfer ?
