### ISSUE TITLE
Error while adding to cart

### ISSUE THREAD

**Issue by ballonnetje** [dclipca/eckmar#14]
Get this error when adding product to cart:
 Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
No message

Not sure what to do with this. 
Also not able to login as admin, generally because i do not know the login details and also because I think it has something to do with the error above. This because I'm not getting any errors like "your credentials dont match blabla"

**Comment by Gralien** [comment]
To login as an admin on this script you will need to create a userin the site or in users table, then elevate the user to the MYSQL admins table. then when you login as that user, you will have the privileges to see the admin functions of the site. limited but sufficient.

without more info on the cart error, im going to suspect a permissions or ownership error. look into it.

**Comment by ballonnetje** [comment]
So creating an account via the website also does not work. Looks like something in general working behind the forms is.. well.. not working. 
Made a video to hopefully get a better understanding of the error https://streamable.com/5wvqsr

I could add the user via SQL, but than I also need to know (I think) what encoding is used for the password. And maybe other things which I need to know..

**Comment by ballonnetje** [comment]
So when checking out some indian video dude on [youtube](https://www.youtube.com/watch?v=4G5q0sqP-wI) I got it working.. a bit. 
Did not edit anything in the code, but entered this in the terminal while active folder on project root map:
/var/www/public $  composer dump-autoload
/var/www/public $  php artisan serve

This wil start a dev server on port 8000.. not really what I want I think, because why can it not just be running on port 80?
Anyway, while the dev server is active I visited the website on port 8000 and now I get some response out of the signup/in forms. At least I managed to create an account.

**Comment by Gralien** [comment]
add any user to MYSQL admins table and they get admins privs with the same login info preserved.
remember also
php artisan config:clear
php artisan cache:clear
after making adjustments. 

as for the ports 8080 you can circumvent this in your vhosts or sites-enabled for whatever server you are using.

**Comment by Gralien** [comment]
presuming issue closed?

**Comment by ballonnetje** [comment]
Yea sorry for not answering. Issue is resolved.
