### ISSUE TITLE
How to add admin?

### ISSUE THREAD

**Issue by lizard6661** [dclipca/eckmar#16]
You can detailed instructions How to give administrator rights?

**Comment by KlausStortebeker** [comment]
You are kidding no ?

**Comment by Gralien** [comment]
As an administrator you can assign admin rights to users from the admin panel.
To get an initial admin level access you need to add a user to the admins database in MYSQL.

closed issue #7 Login as admin
Step 1. Get your user ID that you want to make as admin from datatable users.
step 2. create new entry in table admins with your user id
step 3. Login with user and you will get admin menu in left side near logo
