### ISSUE TITLE
ERROR Admin View User

### ISSUE THREAD

**Issue by thisisforjimmy** [dclipca/eckmar#18]
ErrorException (E_ERROR)
Class name must be a valid object or a string (View: /www/XXXXX/XXXXX/resources/views/admin/user.blade.php)

 Symfony\Component\Debug\Exception\FatalThrowableError
…/app/VendorPurchase.php101 

I get this anytime in the admin panel and try to view a users account. Any help would be appreciated.

**Comment by Gralien** [comment]
are you trying to view the regular user account that you elevated to admin privileges?
there is a bug there. if its the OG admin elevated account then this error will persist.
make a new regular user account and check again

**Comment by MxZoldyck** [comment]
I got recently this error I still don't know hot to fix it

**Comment by MxZoldyck** [comment]
Edit : when I Try to view vendor account I get this error
