### ISSUE TITLE
xmr - payments

### ISSUE THREAD

**Issue by mathewbuer** [dclipca/eckmar#19]
can anyone point me in the direction of enabling Finalise Early and also XMR Settings for vendor page

ive edited coins.php and marketplace.php, XMR node is all setup and everything else seems to be working fine

**Comment by Gralien** [comment]
Finalize early is an add on module. google and find.
what do you you mean the the xmr settings in the vendor page?
if your .env file is in order and the coins setup in coins.php then the XMR option should appear.
If your node is not running an RPC server along side that its connecting to, then you wont get ballances just a red box

**Comment by mathewbuer** [comment]
i did google for it but i could only find someone selling it.

as for the XMR, once the site is setup and the xmr coin unnlisted in coins.php it never shows on the become a vendor page, it always seems to show STB coin.

also if you diable that coin in coins.php it throws errors

**Comment by Gralien** [comment]
At the top of that file comment out all the coins that you aren't going to be using.  Uncomment XMR.

**Comment by botdigit-admin** [comment]
[mathewbuer](https://github.com/mathewbuer) i have fixed your all issue and you can buy FE from demo.botdigit.com 
XMR was not showing because you did not clear cache.
