### ISSUE TITLE
how exactly do you add userid to admin table?

### ISSUE THREAD

**Issue by DMT-Psychonaut** [dclipca/eckmar#21]
how exactly do you add userid to admin table?

**Comment by charon-iv6** [comment]
u can 2 it in 2 ways : 1 - run the "php artisan db:seed" then change the admin user id or just copy ur user id from users table then add it there (u can install phpmyadmin in the /var/www/market/public path so u can access mysql db easier)

**Comment by dclipca** [comment]
Closing this as it seems the issue is solved.
