### ISSUE TITLE
daemon 

### ISSUE THREAD

**Issue by mexx666** [dclipca/eckmar#4]
how connect xmr and btc daemons , they aren't in the same server as marketplace.  or need to create local network 10.0.0.1/2 and upfront with 127.....0 ,  in the install pdf is only explanation to enter in the env.file 
bitcoind_host=server ip
por
user
pass , there is the main issue for me.

**Comment by dclipca** [comment]
> how connect xmr and btc daemons , they aren't in the same server as marketplace. or need to create local network 10.0.0.1/2 and upfront with 127.....0 , in the install pdf is only explanation to enter in the env.file
> bitcoind_host=server ip
> por
> user
> pass , there is the main issue for me.

You need to host your own daemon. I don't think provided in this package.

**Comment by mexx666** [comment]
i know that need to host own daemon, like i was saying the daemons are in the different server and marketplace is in the other one.  so how to connect them , or need to connect with local network 10.0.0.1/2 and upfront it with 127.0.0.1 , and yes in this package i cant find anything about the daemons connections, maybe you know the solution?

**Comment by dclipca** [comment]
> i know that need to host own daemon, like i was saying the daemons are in the different server and marketplace is in the other one. so how to connect them , or need to connect with local network 10.0.0.1/2 and upfront it with 127.0.0.1 , and yes in this package i cant find anything about the daemons connections, maybe you know the solution?

Idk unfortunately. Can you post what you tried to do? Maybe others can help you.
