### ISSUE TITLE
how to login with as admin to get in admin panel

### ISSUE THREAD

**Issue by ubback2** [dclipca/eckmar#7]
how to login with an admin

**Comment by ubback2** [comment]
to get into admin panel

**Comment by botdigit-admin** [comment]
Login as admin 
**Step 1.** Get your user ID  that you want to make as admin from datatable users.
**step 2.** create new entry in table admins with your user id 
**step 3.** Login with user and you will get admin menu in left side near logo 

![Screenshot 2021-10-30 at 12 02 51 PM](https://user-images.githubusercontent.com/28224590/139523066-59164e92-4835-41a8-ba57-e357ffdf3933.png)
