### ISSUE TITLE
Create new page ?

### ISSUE THREAD

**Issue by olas2** [dclipca/eckmar#8]
I want to create a custom page using the header or something else, how can I make it accessible?
Thanks

**Comment by botdigit-admin** [comment]
create new blade page check laravel doc

like 

The easiest way in Laravel is to define a route closure, and return a view from it.

In your routes/web.php file:

Route::get('/my-page', function () {
    return view('my-page');
});
Then in resources/views you create a file called my-page.php, or if you want to use Laravel's Blade syntax (you probably do) call it my-page.blade.php.

**Comment by olas2** [comment]
Thanks, or I have a problem with including the nav bar, menu etc ...

**Comment by botdigit-admin** [comment]
You can include navbar menus like this 
@include('master.navbar') //in master directory navbar.blade.php
@include('master.search')
